route:
  group_by: 
    - HighCpuUsage
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'telepush'

receivers:
- name: 'telepush'
  webhook_configs:
  - send_resolved: true
    url: 'https://telepush.dev/api/inlets/alertmanager/570659'
