groups:
- name: example
  rules:
  - alert: HighCpuUsage
    expr: 100 - (irate(node_cpu_seconds_total{mode='idle',check='CPU'}[1m]) * 100) > 80
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage is above 80%:  (current value: {{ humanize $value }})"

  - alert: HighMemoryUsage
    expr: 100 * ((node_memory_MemTotal_bytes{check='Memory'} - node_memory_MemFree_bytes{check='Memory'} - node_memory_Buffers_bytes{check='Memory'} - node_memory_Cached_bytes{check='Memory'}) / node_memory_MemTotal_bytes{check='Memory'}) > 70
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory left is more than 70%:  (current value: {{ humanize $value }})"