groups:
- name: example
  rules:
  - alert: HighCpuUsage
    expr: 100 - (irate(node_cpu_seconds_total{mode='idle',check='CPU'}[1m]) * 100) > 80
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage is above 80%:  (current value: {{ humanize $value }})"

  - alert: HighMemoryUsage
    expr: 100 - (rate(node_memory_MemAvailable_bytes{check='Memory'}[1m]) / node_memory_MemTotal_bytes{check='Memory'} * 100) < 20
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Free memory left is less than 20%:  (current value: {{ humanize $value }})"